# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cec3ceb4e2a50fd313adb563317291184a164ba107957d139a336c0d6729bdc0b1800dbb494ebb5cdd40acee489d4c4507045a68c34661c9952409a2d448706

test:
  secret_key_base: bf6262e2236d473efe6fe56153696c797b1ce4b266fb62200133deee2f09d174a70de5945476c8ebf68ab9abd2085c355028414534d9ed61316483d5a57a7fdd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
